#!/usr/bin/env bash
# Generate llms.txt (index) and llms-full.txt (full content) from knowledge/.
# See https://llmstxt.org for the format. Run from anywhere: ./scripts/build-llms.sh
set -euo pipefail

cd "$(dirname "$0")/.."

RAW="https://raw.githubusercontent.com/openapi/openapi-llm-wiki/main"
CORE=(company-profile services-catalog platform-guide faq references)

title_of() { sed -n '1s/^# //p' "$1"; }
base_url_of() { sed -n 's/^- \*\*Base URL\*\*: `\(.*\)`$/\1/p' "$1" | head -n1; }

{
  echo "# Openapi LLM Wiki"
  echo
  echo "> LLM-optimized knowledge base for the Openapi® API marketplace (https://openapi.com):"
  echo "> company profile, platform guide (OAuth v2, scopes, billing, sandbox, async patterns),"
  echo "> API catalog, per-service endpoint references and the official OpenAPI 3 specs."
  echo
  echo "Load \`platform-guide.md\` together with any service page: it covers authentication and"
  echo "billing, which every service shares. The full knowledge base in one file is at"
  echo "${RAW}/llms-full.txt"
  echo
  echo "## Core"
  echo
  for name in "${CORE[@]}"; do
    f="knowledge/${name}.md"
    echo "- [$(title_of "$f")](${RAW}/${f})"
  done
  echo
  echo "## Services"
  echo
  for f in knowledge/services/*.md; do
    name=$(basename "$f" .md)
    echo "- [$(title_of "$f")](${RAW}/${f}): base URL $(base_url_of "$f"), OpenAPI spec ${RAW}/knowledge/oas/${name}.openapi.json"
  done
  echo
  echo "## Optional"
  echo
  echo "- [Spec source URLs](${RAW}/knowledge/oas/00-list.txt): canonical download URLs of every OpenAPI spec"
  echo "- [Repository](https://github.com/openapi/openapi-llm-wiki): source, issues and releases"
} > llms.txt

{
  echo "# Openapi LLM Wiki (full)"
  echo
  echo "> All Markdown files of https://github.com/openapi/openapi-llm-wiki concatenated."
  echo "> Generated by scripts/build-llms.sh, do not edit by hand."
  for f in "${CORE[@]/#/knowledge/}"; do
    printf '\n---\n<!-- source: %s.md -->\n\n' "$f"
    cat "$f.md"
  done
  for f in knowledge/services/*.md; do
    printf '\n---\n<!-- source: %s -->\n\n' "$f"
    cat "$f"
  done
} > llms-full.txt

echo "Generated llms.txt ($(wc -l < llms.txt) lines) and llms-full.txt ($(wc -c < llms-full.txt) bytes)"
